### PR TITLE
paging

### PR DESCRIPTION
**Pull request by AVCADO**
did some more paging stuff. should work now!

### CODE REVIEW

**Comment by AVCADO** [comment]
ci is dumb

**Comment by pontaoski** [comment]
Needs rebase.

**Comment by AVCADO** [comment]
rebased #11 , ready for review.

**Comment by pontaoski** [comment]
Mark as draft; this isn't anywhere near close to being a completed feature that can be merged.

**Comment by AVCADO** [comment]
if you say "oh it's not near completed paging", why don't you do it yourself? I'm going to merge it. I tried my absolute hardest to get paging working and all I get in return is "not good enough". Therefore, I am going to merge it. I can tell you're gonna get very angry at me, but it works on **MY MACHINE.**...

**Pull request closed without merging**
