### PR TITLE
feat: strip debug symbols in kernel, use separate file

### PR DESCRIPTION
**Pull request by pontaoski**

### CODE REVIEW

**Comment by rizet** [comment]
What's the output of `objump -x NovaVita.kernel`?

**Comment by AVCADO** [comment]
Why would there be a `.kernel`? Aren't kernels `.bin`?

**Comment by rizet** [comment]
lmao have you even looked through the repo? it outputs as `NovaVita.kernel`

**Comment by Vresod** [comment]
it builds a .kernel file which is the same format and stuff as a .bin file but the extensions is different

**Comment by rizet** [comment]
i don't think the file extension matters at all in osdev. when developing in userspace, extensions are useful for file associations, etc. however in osdev it doesn't matter because it's just a filename. as long as the file structure and content is the same.

**Comment by pontaoski** [comment]
> What's the output of `objump -x NovaVita.kernel`?

```
 ➜ objdump -x ./iso/System/Kernel/NovaVita.kernel 

./iso/System/Kernel/NovaVita.kernel:     file format elf32-i386
./iso/System/Kernel/NovaVita.kernel
architecture: i386, flags 0x00000102:
EXEC_P, D_PAGED
start address 0x08049278

Program Header:
    LOAD off    0x00000000 vaddr 0x000ff000 paddr 0x000ff000 align 2**12
         filesz 0x00002000 memsz 0x00002000 flags r--
    LOAD off    0x00002000 vaddr 0x08049000 paddr 0x08049000 align 2**12
         filesz 0x00002000 memsz 0x00002000 flags r-x
    LOAD off    0x00004000 vaddr 0x0804b000 paddr 0x0804b000 align 2**12
         filesz 0x00001118 memsz 0x00001118 flags r--
    LOAD off    0x00005f64 vaddr 0x0804df64 paddr 0x0804df64 align 2**12
         filesz 0x0000109c memsz 0x0000909c flags rw-
   STACK off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**4
         filesz 0x00000000 memsz 0x00000000 flags rwx
   RELRO off    0x00005f64 vaddr 0x0804df64 paddr 0x0804df64 align 2**0
         filesz 0x0000009c memsz 0x0000009c flags r--

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         00002000  08049000  08049000  00002000  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .rodata       00001000  0804b000  0804b000  00004000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .eh_frame     00000118  0804c000  0804c000  00005000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .got          0000009c  0804df64  0804df64  00005f64  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  4 .got.plt      0000000c  0804e000  0804e000  00006000  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  5 .data         00000ff4  0804e00c  0804e00c  0000600c  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  6 .bss          00008000  0804f000  0804f000  00007000  2**12
                  ALLOC
  7 .comment      0000002c  00000000  00000000  00007000  2**0
                  CONTENTS, READONLY
  8 .multiboot    00001000  00100000  00100000  00001000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  9 .gdt          00000000  00101000  00101000  0000702c  2**0
                  CONTENTS
 10 .gnu_debuglink 0000001c  00000000  00000000  0000702c  2**2
                  CONTENTS, READONLY
SYMBOL TABLE:
no symbols
```

**Comment by rizet** [comment]
epic.

**Comment by AVCADO** [comment]
merge?

**Comment by rizet** [comment]
merge.

**Comment by AVCADO** [comment]
merged

**Comment by rizet** [comment]
merged?

**Comment by rizet** [comment]
epic

**Pull request merged**
